name: 'Natrio Build'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  check-links: 
    runs-on: ["windows", "self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unity - Builder
        uses: game-ci/unity-builder@v3.0.0  
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL